apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: kastrov/review-service:latest
        ports:
        - containerPort: 84
        env:
        - name: DB_HOST
          value: "mysql-db"
        - name: DB_USER
          value: "hotel_user"
        - name: DB_PASSWORD
          value: "hotel_pass"
        - name: DB_NAME
          value: "hotel_booking"
        - name: DB_PORT
          value: "3306"
        livenessProbe:
          httpGet:
            path: /health
            port: 84
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 84
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: hotel-booking
spec:
  selector:
    app: review-service
  ports:
  - port: 84
    targetPort: 84
  type: ClusterIP
