apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: kastrov/user-service:latest
        ports:
        - containerPort: 83
        env:
        - name: DB_HOST
          value: "mysql-db"
        - name: DB_USER
          value: "hotel_user"
        - name: DB_PASSWORD
          value: "hotel_pass"
        - name: DB_NAME
          value: "hotel_booking"
        - name: DB_PORT
          value: "3306"
        - name: SECRET_KEY
          value: "your-secret-key-here"
        livenessProbe:
          httpGet:
            path: /health
            port: 83
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 83
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: hotel-booking
spec:
  selector:
    app: user-service
  ports:
  - port: 83
    targetPort: 83
  type: ClusterIP
